version: "3"
services:

  airflow:
    container_name: airflow_container
    build: ./airflow
    ports: 
      - "8080:8080"
    volumes:
      - ./airflow/dags:/app/airflow/dags
    extra_hosts:
      - "outside:${HOST_IP}"
