version: "3.5"
services:
  data-lake-efk-worker:
    container_name: data-lake-efk-worker
    build: .
    ports:
    - "${ENV_EXPRESS_PORT:-5000}:5000"
    volumes:
    - "${ENV_NODE_APPDIR:-.}:/code"
    environment:
      ENV_MONGO_URL: "${ENV_MONGO_URL}"
      ENV_ELASTICSEARCH_URL: "${ENV_ELASTICSEARCH_URL}"
    networks:
      dataLake:
        aliases:
          - data-lake-efk-worker
      logAggregator:
        aliases:
          - data-lake-efk-worker

networks:
  dataLake:
    external: true
  logAggregator:
    external: true
